### ISSUE TITLE
It would be really nice to have on Maven Central

### ISSUE THREAD

**Issue by levonk** [linkedin/URL-Detector#2]
Thanks for the logic!  Any chance you're planning on deploying to Maven central?

**Comment by tzuhanjan** [comment]
This is an excellent suggestion. I'll work on getting this onto Maven.

**Comment by alexeygrigorev** [comment]
+1

**Comment by houseDaine** [comment]
+1

**Comment by 0312birdzhang** [comment]
+1

**Comment by tzuhanjan** [comment]
Taking longer than expected. This will get done eventually.

**Comment by purplepapa** [comment]
+1

**Comment by srchulo** [comment]
+1!!

**Comment by namitmr** [comment]
+1!!

**Comment by zadkiel87** [comment]
+1!!

**Comment by tzuhanjan** [comment]
Uploaded to Maven Central:

http://repo1.maven.org/maven2/com/linkedin/urls/url-detector/

**Comment by jotomo** [comment]
:+1:  Thanks @tzuhanjan!

Maven coordinates are:
```xml
<dependency>
    <groupId>com.linkedin.urls</groupId>
    <artifactId>url-detector</artifactId>
    <version>0.1.17</version>
</dependency>
```
