### ISSUE TITLE
Support for local Maven repository installation

### ISSUE THREAD

**Issue by pmonks** [linkedin/URL-Detector#6]
In the interim, while issue #2 is being worked on, it would be ideal if it were possible to install the url-detector library in the local Maven repository (typically `~/.m2/repository/`), so that other Maven-based build tools can consume the library.

Note that issue #2 is a vastly preferable solution to this problem, but allowing local installation (this issue) provides a short-term workaround.

**Comment by tzuhanjan** [comment]
Solved in #2
