### ISSUE TITLE
Using URL-Detector with Maven: jitpack stopgap

### ISSUE THREAD

**Issue by igorbrigadir** [linkedin/URL-Detector#8]
While #6 and #2 is still being resolved, as a temporary workaround, you can use [Jitpack](https://jitpack.io/#linkedin/URL-Detector/2a0fede05e):

add:

```
...

<repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

....

<dependency>
        <groupId>com.github.linkedin</groupId>
        <artifactId>URL-Detector</artifactId>
        <version>2a0fede05e</version>
    </dependency>
```

to your pom.xml.

**Comment by pmonks** [comment]
Ooooh that's nice - is this a URL-Detector issue though?  Seems more like a comment on issue #2 and/or issue #6.

Also, do you know if there's an equivalent for Leiningen (the build tool I'm using)?

**Comment by igorbrigadir** [comment]
Ah yeah, should have commented instead of creating a new issue.

Looks like Jitpack should work with leiningen too: https://github.com/jitpack/jitpack.io/blob/master/BUILDING.md#leiningen-projects

**Comment by pmonks** [comment]
Yeah I saw that Jitpack can build Leiningen projects, but I was wondering whether it can be leveraged from within a Leiningen project, to consume projects on Github?

**Comment by tzuhanjan** [comment]
Thanks for the suggestion for Jitpack. It's a pretty cool tool. #2 is now resolved, as is this since it's now on Maven.
